### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by nagamalli148** [agrueneberg/crochet#9]
Hi @agrueneberg  

It would be helpful if the repository has a  License File. It is showing as MIT expat in Description but it would be better if we had a clear Licence.md file

**Comment by agrueneberg** [comment]
Hello,

this is standard practice for writing R extensions, see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing. I agree that it doesn't follow GitHub conventions, but you wouldn't look at this package unless you are an R user anyway.

Thanks,
Alex

**Comment by nagamalli148** [comment]
Hi Actually i am trying to build a package for guix for the r-crochet package you have authored. There is a need for licence to be added along. Hence i looked for the licence. So it belongs to MIT Licence right?

**Comment by agrueneberg** [comment]
OK, thank you for clarifying that. Yes, the package is under MIT license.
